#!/bin/bash
# File: /usr/local/sbin/unlock_limit_ip_user_ssh_notif

user="$1"
BOT_FILE="/etc/bot/limitip.db"

if id "$user" &>/dev/null; then
    passwd -u "$user" > /dev/null

    # Ambil token & id Telegram bot limit IP
    if [[ -f "$BOT_FILE" ]]; then
        BOT_TOKEN=$(grep '#bot#' "$BOT_FILE" | awk '{print $2}')
        CHAT_ID=$(grep '#bot#' "$BOT_FILE" | awk '{print $3}')

        # Kirim notifikasi
        TEXT="Akun SSH *$user* telah dibuka kembali setelah terkunci karena melebihi limit IP."
        curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="$TEXT" \
            -d parse_mode="Markdown" > /dev/null
    fi
fi
